{{- if .Values.image.tag }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: kargo-demo-content
data:
  index.html: |-
    <!DOCTYPE html>
    <html>
    <head>
    <title>{{ .Values.env | default "dev" }}</title>
    </head>
    <body>
    <h1>{{ .Values.env | default "dev" }}</h1>
    </body>
    </html>
{{- end }}